modLoader="javafml"
loaderVersion="[28,)"
[[mods]] #mandatory
modId="aequivaleo"
version="${file.jarVersion}"
displayName="Aequivaleo"
authors="OrionOnline, LDTTeam"
description='''
Mediator mod which allows for high performance analysis of recipes, their inputs and outputs.
'''
